services:
    twig.extension.renderList:
        class: Kristofvc\ListBundle\Twig\Extension\ListExtension
        arguments: ["@service_container"]
        tags:
            -  { name: twig.extension }